From I.Duff@rl.ac.uk Wed Jan  4 04:55:43 2006
Date: Wed, 4 Jan 2006 11:29:41 GMT
From: Iain Duff <I.Duff@rl.ac.uk>
To: Copper.Conference@colorado.edu, I.Duff@rl.ac.uk
Cc: elman@cs.umd.edu, tmanteuf@boulder.colorado.edu
Subject: Re: Workshops at Copper

Cathy

Happy New Year

Here are abstacts for the two Copper Workshops.  Might it be possible to
put them on the Web site for the Conference?  I note that Craig is
suggesting another meeting place for his workshop (last sentence of abstract).
Is this doable ... given we don't usually get a huge number of people
at the workshop.

Are you block booking rooms for committee etc?  Di is coming as well so
we would want our usual one bedroom condo.

Best wishes for 2006

Iain

+++++++++++++++++++++++++++++++++++++++++++++++++++++


Monday night workshop.  April 3

Simulation Based Optimization.
George Biros and Eldad Haber

Simulation is a powerful tool in science and engineering for predicting 
the behavior of physical systems, particularly those that are governed 
by partial differential equations. Moreover, progress in algorithms and 
computational hardware has been responsible for improvements in 
simulation. Using today's simulation tools it has now become practical 
to consider complex design problems, where we wish to determine 
parameters of large systems that maximizes a certain objective, and 
inverse problems where we wish to determine parameters whose behavior 
matches measured data. Examples of design problems include structural 
optimization, antenna design and process optimization. Geophysical 
imaging, biomedical imaging, weather data assimilations are just a few 
examples of inverse problems where the physics is governed by partial 
differential equations.

While these types of problems are naturally posed as optimization 
problems, they offer new challenges because of their large size, inexact 
derivatives (when available), and ill-posedness. Current software cannot 
be used because matrices of constraint gradients cannot be factored, and 
computing with null space bases can be exceedingly expensive. The goal 
of this workshop is to review methods for PDE-optimization problems
and to expose researches to some open problems in the field.

++++++++++++

Wednesday night workshop.  April 5

Dynamic Data Driven Liquid Flows
Craig Douglas

This workshop will be strictly hands on. It will introduce DDDAS techniques 
(see http://www.dddas.org) including dynamic modeling, errors, sensor 
operation, and the symbiotic relations between the sensors and the application.

We will simulate the level of a liquid in media that is porous in one boundary 
edge only and design from scratch an algorithm to maintain it at a fixed level 
on average even though the liquid is disappearing through the open boundary 
using a random step function.

We will develop convergence results initially using a semi-direct method, but 
some of the participants may end up with a random walk by the end of the 
workshop. We will iterate on the liquid problem until we develop a fast 
iterative (and convergent) algorithm that we have thoroughly tested. We will 
use the data from experiments to drive the entire methodology and the 
algorithms will drive how and when data is collected.

This workshop will be held in one of the local watering holes, not in the 
conference center. Sensor oversight and correction will be provided at 
the tables.
